apiVersion: apps/v1
kind: Deployment
metadata:
  name: compute-kart-frntnd
  namespace: computekart
spec:
  replicas: 1
  selector:
    matchLabels:
      app: compute-kart-frntnd
  template:
    metadata:
      labels:
        app: compute-kart-frntnd
    spec:
      containers:
        - name: frontend
          image: kumarsubrato/computekart-frontend:v0.0.5          execSync(`sudo docker build -t kumarsubrato/computekart-frontend:${version} -f ${__dirname}/docker/Dockerfile ${__dirname}/../..`, { stdio: 'inherit' });    
          ports:
            - containerPort: 80