db {
  url = ${?DB_URL}
  username = ${?DB_USER}
  password = ${?DB_PASS}
  driver = "com.mysql.cj.jdbc.Driver"
  poolSize = ${?DB_POOL_SIZE}
}

crypto {
  secretKey = ${?CRYPTO_SECRET_KEY}
}

servers {
  networkserver = ${?NETWORK_SERVER_URL}
}

akka.http.server {
  request-timeout = 30s
}